name: ekkagata
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  flutter_bloc: ^8.1.3
  connectivity_plus: ^4.0.1
  http:
  equatable: ^2.0.5
  hydrated_bloc: ^9.1.2
  path_provider: ^2.1.0
  lottie: ^2.6.0
  fluttertoast: ^8.2.1
  json_annotation: ^4.8.1
  intl: ^0.18.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_app_name: ^0.1.1
  # change_app_package_name: ^1.1.0
  # flutter_launcher_icons: ^0.13.1


flutter_app_name:
  name: "Ekaggata"


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app-brand.jpeg"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
